### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/e-s1-evaluacion-intermedia-katherinebl#1]
Great job @katherinebl! Good exercise, clean and tidy, the page looks nice in a web browser although we have some work to do mainly with the HTML code.
Here we have some tips to improve your exercise:
- [x] Menu items should be clickable, so we are going to need some links
- [x] the page logo should be clickable as well
- [x] The header must have a fixed position not only the menu containers
- [x] The menu elements should be wrapped around a `NAV` tag
- [x] The `MAIN` tag could be the main section or contains a section. If we maintain the `.container`element, it should be a `SECTION` tag, and we  should style it accordingly 
- [x] If there were justice in the world, there should be only one `H1` per page
- [x] `font-family` is an inheritable property so that it shouldn't be applied to a `* {}` selector. We often use it inside the `body {}` selector
- [x] Remember that `block` elements don't need to have set a width property up to 100% nor 100vw

That's it, let me know if you have any doubts ;)

**Comment by katherinebl** [comment]
Thank you for the corrections @oneeyedman !

I try to finish all the tasks in order to enhance my exercise, I did 7/8 tasks in a new branch (enhancement) and then I merged it with the master branch.

I have a problem when I tried to _fix the header position_: when I did it all the viewport got aquamarine and the elements out of order, let me show you an image to clarify my point.

![header con position fixed](https://user-images.githubusercontent.com/44637185/48372495-1299a000-e6bf-11e8-800a-f6d03ded863c.png)

That's why I didn't check that point in the issues list, let me know if I'm missing something. I think the rest works just fine. Please, keep me post... thanks! :)
